{
  "formatVersion": "1.1",
  "component": {
    "group": "com.teegarcs.ktools",
    "module": "ktools-plugin",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktools-plugin-0.1.0.jar",
          "url": "ktools-plugin-0.1.0.jar",
          "size": 29352,
          "sha512": "0d49680adc36ceb58db3d1789a7689882799d2f87f2291ec55c72e50d7f304a2ad5c39e0c880e57c58ac372ee91d21dee6d135200df4833d729f10dba23c134d",
          "sha256": "04f2a5af29a357cdc0fa9234977f31c49cc98b20bec503681d41dff968b87f2d",
          "sha1": "d7f7e79a4409fc6e696abbe440e1ccfd4174e034",
          "md5": "04165458ce91683a825eb0042f88f26c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "ktools-plugin-0.1.0.jar",
          "url": "ktools-plugin-0.1.0.jar",
          "size": 29352,
          "sha512": "0d49680adc36ceb58db3d1789a7689882799d2f87f2291ec55c72e50d7f304a2ad5c39e0c880e57c58ac372ee91d21dee6d135200df4833d729f10dba23c134d",
          "sha256": "04f2a5af29a357cdc0fa9234977f31c49cc98b20bec503681d41dff968b87f2d",
          "sha1": "d7f7e79a4409fc6e696abbe440e1ccfd4174e034",
          "md5": "04165458ce91683a825eb0042f88f26c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ktools-plugin-0.1.0-sources.jar",
          "url": "ktools-plugin-0.1.0-sources.jar",
          "size": 9243,
          "sha512": "32d2f1546fabeea574585a9b256e06ccc1a88ef4b001211d4571e2d6ceec62d645eba7555845b44fbc4a2705b8073463b103af5de03ca2ea06191df8534b3baa",
          "sha256": "166f6fc4b843cdebb908c62e9a9f2dc885416540a2b69fbbe4896c9d1a82e631",
          "sha1": "917332b40c17d6e86ae26d79e7fc5febca6516ad",
          "md5": "84adb44c53d3bf6f682aefa715813ec1"
        }
      ]
    }
  ]
}
